remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title : Nick van Oort's Data Science Portfolio
description : A collection of my Deep Learning & Deployment and Ethics & Privacy study exercises and Hackathon project
