[model]
training = true
[model.config]
matrixshape = [28, 28]
batchsize = 64
input_channels = 1
hidden = 80
kernel_size = 5
maxpool = 2
num_layers = 2
num_classes = 10


[types]
training = "bool"
config = "dict"
