[model]
epochs = 20
metrics = ["Accuracy"]
logdir = "C:\Users\NvanOort\Code\MADS\DLDEPL\portfolio-NTvanOort\2-hypertuning-mlflow\models"
train_steps = 100
valid_steps = 100
reporttypes = ["ReportTypes.MLFLOW", "ReportTypes.TOML"]
[model.optimizer_kwargs]
lr = 0.0015
weight_decay = 0.0001

[model.scheduler_kwargs]
factor = 0.1
patience = 10

[model.earlystop_kwargs]
save = false
verbose = true
patience = 10


[types]
epochs = "int"
metrics = "list"
logdir = "WindowsPath"
train_steps = "int"
valid_steps = "int"
reporttypes = "list"
optimizer_kwargs = "dict"
scheduler_kwargs = "dict"
earlystop_kwargs = "dict"
